name = "invitation-maker"
compatibility_date = "2024-01-15"
pages_build_output_dir = "frontend/out"

[env.production]
name = "invitation-maker-production"
pages_build_output_dir = "frontend/out"

[build]
command = "npm run build"

[build.upload]
dir = "frontend/out"

[build.environment]
CF_SECURITY_HEADERS = "enabled"
