name = "invitation-maker"
compatibility_date = "2024-01-15"

pages_build_output_dir = "frontend/out"

[build]
command = "npm install && npm run build"
cwd = "frontend"

[vars]
CF_SECURITY_HEADERS = "enabled"
CF_COOP = "same-origin"
CF_COEP = "require-corp"
CF_CORP = "cross-origin"

[env.staging]
name = "invitation-maker-staging"

[env.production]
name = "invitation-maker-production"

[env.production.vars]
CF_SECURITY_HEADERS = "enabled"
CF_COOP = "same-origin"
CF_COEP = "require-corp"
CF_CORP = "cross-origin"
